package com.big.dreamer.doccentral.document.carsale.template;

public final class CarSaleTemplates {

    private CarSaleTemplates() {
    }

    static final String LEGACY_PEOPLE_DOCUMENT = "NOSOTROS: :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, con Documento Único de Identidad número: :document y con Numero Identificación Tributaria: :nit, que me denominaré “:gender” y :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, con Documento Único de Identidad número: :document y con Numero Identificación Tributaria: :nit, que me denominaré “:gender”, ";
    static final String LEGACY_PEOPLE_AUTHENTIC = "COMPARECEN: :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, a :identifiesSeller e identifico por medio de su Documento Único de Identidad número: :document y con Numero Identificación Tributaria: :nit, que me denominaré “:gender” y :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, :identifiesBuyer e identifico por medio de su Documento Único de Identidad número: :document y con Numero Identificación Tributaria: :nit, que me denominaré “:gender” y, ";
    static final String LEGACY_DOCUMENT = "EN CALIDAD DE :garment :institution ,. II) que por el precio de :price  DOLARES DE LOS ESTADOS UNIDOS DE AMERICA, que el primero  vende al segundo el vehículo descrito, haciéndole la tradición del dominio, posesión y demás derechos anexos que sobre el mismo le corresponden, entregándoselo materialmente desde este momento, junto con sus llaves y respectivos documentos de propiedad. III) Por su parte el comprador acepta la venta y tradición que el dominio, posesión y demás derechos anexos que sobre el vehículo vendido que se le hacen, dándose por recibido en este momento del mismo. IV) El comprador manifiesta que ha revisado a su satisfacción el vehículo que compro juntamente con la documentación que le entrega el vendedor. V) Ambos contratantes para los efectos legales de este instrumento, señalan como domicilio especial el de esta ciudad, a cuyos tribunales se someten en caso de acción judicial por reclamación de vicios ocultos en el vehículo vendido. ";

    public static final String PEOPLE_DOCUMENT = "NOSOTROS: :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, con Documento Único de Identidad número: :document, que me denominaré “:gender” y :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, con Documento Único de Identidad número: :document, que me denominaré “:gender”, ";
    public static final String PEOPLE_AUTHENTIC = "COMPARECEN: :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, a :identifiesSeller e identifico por medio de su Documento Único de Identidad número: :document, que me denominaré “:gender” y :givenName :lastName, de :age años de edad, :job, del domicilio de :settlement, Departamento de :state, :identifiesBuyer e identifico por medio de su Documento Único de Identidad número: :document, que me denominaré “:gender” y, ";
    public static final String CAR_DOCUMENT = "OTORGAMOS: I) Que el primero de los comparecientes es dueño y actual poseedor de un vehículo automotor usado, de las siguientes características: PLACAS: :licensePlate; MARCA: :brand; MODELO: :model; COLOR: :color; AÑO: :factoryYear; CAPACIDAD: :capacity; DOMINIO AJENO: :domain; CLASE: :vehicleClass; NÚMERO DE MOTOR: :engineNumber; NÚMERO DE CHASIS: :chassisNumber; NÚMERO VIN: :vinNumber; ";
    public static final String CAR_AUTHENTIC = "ME DICEN: I) Que reconocen como  suyas  las firmas que calzan el anterior documento que contiene  un  contrato de compraventa de vehículo,  en el cual la primera de los comparecientes es dueño y actual poseedor de un vehículo automotor usado, de las siguientes características: PLACAS: :licensePlate; MARCA: :brand; MODELO: :model; COLOR: :color; AÑO: :factoryYear; CAPACIDAD: :capacity; DOMINIO AJENO: :domain; CLASE: :vehicleClass; NÚMERO DE MOTOR: :engineNumber; NÚMERO DE CHASIS: :chassisNumber; NÚMERO VIN: :vinNumber; ";
    public static final String DOCUMENT = "EN CALIDAD DE :garment :institution ,. II) que por el precio de :price  DOLARES DE LOS ESTADOS UNIDOS DE AMERICA, que el primero  vende al segundo el vehículo descrito, haciéndole la tradición del dominio, posesión y demás derechos anexos que sobre el mismo le corresponden, entregándoselo materialmente desde este momento, junto con sus llaves y respectivos documentos de propiedad. III) Por su parte el comprador acepta la venta y tradición que el dominio, posesión y demás derechos anexos que sobre el vehículo vendido que se le hacen, dándose por recibido en este momento del mismo. IV) El comprador manifiesta que ha revisado a su satisfacción el vehículo que compro juntamente con la documentación que le entrega el vendedor. V) El comprador se obliga a presentar el presente documento ante SERTRACEN para los trámites de inscripción y traspaso correspondientes. VI) Ambos contratantes para los efectos legales de este instrumento, señalan como domicilio especial el de esta ciudad, a cuyos tribunales se someten en caso de acción judicial por reclamación de vicios ocultos en el vehículo vendido. ";
    public static final String FIRST_SECTION_END = "Así nos expresamos ratificando en todas sus partes el contenido del presente contrato en fe de lo cual ambos contratantes firmamos en la ciudad de :settlement,  Departamento de :state, en la fecha del :signDate.-";
    public static final String SECOND_SECTION_END = "DOY FE que las firmas en referencia son AUTENTICAS por haber sido puestas a mi presencia de sus puños y letra por los comparecientes. Así se expresaron los comparecientes, a quienes expliqué los efectos legales de esta acta notarial que consta de dos hojas útiles y leída que se las hube íntegramente en un sólo acto sin interrupción, manifiestan su conformidad, ratifican su contenido y firmamos, DOY FE.-";
    public static final String LEGAL_AUTHENTIC = "En la ciudad de :settlement, Departamento de :state, a las :signHour del día :signDate.- Ante mí, :givenName :lastName, :gender, del domicilio de :settlement, del departamento de :state, ";
}
