package com.big.dreamer.doccentral.document.mutual.template;

import com.big.dreamer.doccentral.document.template.EditableTemplateRepository;
import com.big.dreamer.doccentral.storage.ApplicationDirectories;
import org.springframework.stereotype.Component;
import java.util.List;
import java.util.Map;

@Component
public class MutualTemplateRepository extends EditableTemplateRepository {
    private static final String LEGACY_CONTRACT = "NOSOTROS: :debtor, que en lo sucesivo me denominaré \":debtorRole\"; y :creditor, que en adelante me denominaré \":creditorRole\", por medio del presente instrumento OTORGAMOS un CONTRATO DE MUTUO SIMPLE, sujeto a las siguientes cláusulas: :clauses En :signingPlace, departamento de :signingState, a :signingDate.";
    private static final String LEGACY_INTEREST = "III) INTERESES: La suma mutuada devengará :monthlyInterest por ciento de interés mensual y, en caso de mora, :defaultInterest por ciento mensual adicional, sin exceder la tasa máxima legal vigente.";
    private static final String LEGACY_PAYMENT_SCHEDULE = ":number PLAN DE PAGOS: Capital :capital; intereses :interest; total a pagar :total. :periodicity. Vencimientos: :schedule.";

    public MutualTemplateRepository(ApplicationDirectories directories) {
        super(directories.templatesDirectory("mutual"), List.of(
            new Definition("contract.txt", "Contrato", "Contrato", "", "NOSOTROS: :debtor, que en lo sucesivo me denominaré \":debtorRole\"; y :creditor, que en adelante me denominaré \":creditorRole\", por medio del presente instrumento OTORGAMOS un :mutualType, sujeto a las siguientes cláusulas: :clauses En :signingPlace, departamento de :signingState, a :signingDate."),
            new Definition("principal.txt", "Capital mutuado", "Contrato", "", "I) MUTUO: :debtorSubject recibe a su entera satisfacción :fromCreditor la cantidad de :amount."),
            new Definition("payment.txt", "Plazo y forma de pago", "Contrato", "", "II) PLAZO Y FORMA DE PAGO: La suma mutuada será cancelada en un plazo de :term, con vencimiento el :dueDate, mediante :installments de :installmentAmount. El pago se depositará en la cuenta :paymentAccount del :paymentBank, a nombre de :creditorName."),
            new Definition("payment-schedule.txt", "Plan de pagos", "Contrato", "Se incluye con el cálculo estructurado.", ":number PLAN DE PAGOS: Capital :capital; intereses :interest; total a pagar :total. Los pagos se realizarán :periodicity. :schedule."),
            new Definition("interest.txt", "Intereses", "Contrato", "Se incluye cuando se indica interés mensual o por mora.", "III) INTERESES: :interestTerms"),
            new Definition("purpose.txt", "Origen y destino de los fondos", "Contrato", "", ":number ORIGEN Y DESTINO DE LOS FONDOS: El crédito se otorga con fondos propios obtenidos lícitamente. :debtorSubject destinará los fondos a :fundsPurpose y pagará la obligación con fondos procedentes de actividades lícitas."),
            new Definition("guarantee.txt", "Garantía", "Contrato", "Se incluye cuando se suscribe una letra de cambio.", ":number GARANTÍA: :debtorSubject suscribe una letra de cambio sin protesto por :amount, :forCreditor, con vencimiento el :guaranteeDueDate. La letra garantiza esta obligación y no constituye una doble obligación."),
            new Definition("personal-guarantee.txt", "Fiador o garante", "Contrato", "Se incluye con garantía personal.", ":number GARANTÍA PERSONAL: :guarantor se constituye fiador solidario de todas las obligaciones del presente mutuo."),
            new Definition("vehicle-pledge.txt", "Garantía prendaria sobre vehículo", "Contrato", "Se incluye con prenda sin desplazamiento sobre vehículo.", ":number GARANTÍA PRENDARIA: Para garantizar todas las obligaciones de este mutuo, la parte deudora constituye prenda sin desplazamiento sobre el vehículo de su propiedad con las características siguientes: placas :licensePlate; año :factoryYear; marca :brand; modelo :model; capacidad :capacity; tipo :vehicleType; clase :vehicleClass; dominio y calidad :domain; color :color; chasis :chassisNumber; motor :engineNumber; VIN :vinNumber. Las partes valúan el vehículo en :valuation. La garantía permanecerá vigente mientras exista saldo pendiente; el vehículo continuará en poder de la parte deudora, quien deberá conservarlo, asumir los tributos que lo graven y no podrá disponer de él en perjuicio de la garantía. Las partes autorizan su inscripción en el Registro de Garantías Mobiliarias para efectos de publicidad y oponibilidad frente a terceros."),
            new Definition("movable-guarantee.txt", "Garantía mobiliaria", "Contrato", "Se incluye con garantía mobiliaria.", ":number GARANTÍA MOBILIARIA: Se constituye garantía sobre los bienes siguientes: :guaranteeDetails."),
            new Definition("mortgage-guarantee.txt", "Garantía hipotecaria", "Escritura pública", "Requiere escritura pública.", ":number GARANTÍA HIPOTECARIA: Se constituye hipoteca sobre el inmueble siguiente: :guaranteeDetails."),
            new Definition("acceleration-causes.txt", "Causales de caducidad", "Contrato", "", ":number CAUSALES DE CADUCIDAD: El plazo caducará y podrá exigirse la totalidad de la deuda por ejecución promovida contra :debtorText o por incumplimiento de cualquiera de las condiciones de este contrato."),
            new Definition("acceleration.txt", "Caducidad del plazo", "Contrato", "", ":number CADUCIDAD DEL PLAZO: La obligación se tendrá por vencida y será exigible en su totalidad en caso de mora o incumplimiento."),
            new Definition("jurisdiction.txt", "Domicilio y renuncias", "Contrato", "", ":number DOMICILIO Y RENUNCIAS: Para los efectos legales, :debtorText señala como domicilio especial :specialDomicile, a cuyos tribunales se somete expresamente. Los gastos judiciales y extrajudiciales ocasionados por este adeudo serán por cuenta de :debtorText.:expenses"),
            new Definition("expenses.txt", "Gastos administrativos", "Contrato", "Se incluye cuando se indican gastos administrativos.", " :debtorSubject pagará :administrativeExpenses por ciento en concepto de gastos administrativos."),
            new Definition("authentic.txt", "Auténtica notarial", "Auténtica", "", "En :signingPlace, departamento de :signingState, a las :signingTime de :signingDate. Ante mí, :notary, :notaryTitle, del domicilio de :notaryPlace, departamento de :notaryState, comparecen :identifiedDebtor, denominado \":debtorRole\", y :identifiedCreditor, denominado \":creditorRole\". ME DICEN: Que reconocen como suyas las firmas puestas en el documento privado anterior y ratifican íntegramente sus declaraciones, obligaciones, pactos y renuncias, documento que literalmente dice: «:contract» YO, :notaryTitle, DOY FE de que las firmas son auténticas por haber sido puestas en mi presencia. Advertí a los otorgantes lo dispuesto en el artículo doscientos veinte del Código Tributario, la Ley Contra el Lavado de Dinero y de Activos y la Ley Contra la Usura. Expliqué los efectos legales de esta acta notarial y, leída íntegramente en un solo acto sin interrupción, ratifican su contenido y firmamos. DOY FE."),
            new Definition("public-deed.txt", "Escritura pública", "Escritura pública", "No genera auténtica separada.", "NÚMERO :deedNumber. En :signingPlace, departamento de :signingState, a las :signingTime de :signingDate. Ante mí, :notary, :notaryTitle, comparecen :debtor y :creditor; y ME DICEN: Que otorgan un :mutualType sujeto a las cláusulas siguientes: :clauses. Expliqué a los comparecientes los efectos legales de este instrumento; leído íntegramente, ratifican su contenido y firmamos. DOY FE."),
            new Definition("person.txt", "Datos de comparecientes", "Compartido", "", ":name, de :age años de edad, :job, del domicilio de :settlement, departamento de :state, con Documento Único de Identidad homologado número :document")),
                Map.of(
                        "contract.txt", List.of(LEGACY_CONTRACT),
                        "interest.txt", List.of(LEGACY_INTEREST),
                        "payment-schedule.txt", List.of(LEGACY_PAYMENT_SCHEDULE)));
    }
}
